# Generated by Django 6.1 on 2026-09-02 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('INCREASE', 'Increase Stock'), ('DECREASE', 'Decrease Stock'), ('DAMAGED', 'Damaged'), ('EXPIRED', 'Expired')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('quantity_before', models.PositiveIntegerField(default=0)),
                ('quantity_after', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('STOCK_IN', 'Stock In'), ('SALE', 'Sale'), ('SALES_RETURN', 'Sales Return'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('DAMAGED', 'Damaged Stock'), ('EXPIRED', 'Expired Stock'), ('CANCELLED_SALE', 'Cancelled Sale')], max_length=30)),
                ('reference_type', models.CharField(choices=[('MANUAL', 'Manual'), ('ORDER', 'Order'), ('SALES_RETURN', 'Sales Return'), ('PURCHASE', 'Purchase'), ('SYSTEM', 'System')], default='MANUAL', max_length=30)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_before', models.PositiveIntegerField()),
                ('quantity_after', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='products.product')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='inventory_i_product_2e3433_idx'), models.Index(fields=['transaction_type', 'created_at'], name='inventory_i_transac_1f1168_idx'), models.Index(fields=['reference_type', 'reference_id'], name='inventory_i_referen_ace22e_idx')],
            },
        ),
    ]
